# Generated by Django 2.1.7 on 2019-03-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellingItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_title_text', models.CharField(max_length=200)),
                ('sell_post_date', models.DateTimeField(verbose_name='date published')),
                ('sell_price', models.IntegerField()),
                ('sell_name', models.CharField(max_length=50)),
                ('sell_mail', models.CharField(max_length=50)),
            ],
        ),
    ]
