# Generated by Django 2.1.7 on 2019-03-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190330_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingitems',
            name='sell_description',
            field=models.TextField(default='Add Description Here', max_length=1000),
            preserve_default=False,
        ),
    ]
