# Generated by Django 2.1.7 on 2019-04-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingitems',
            name='id',
        ),
        migrations.AddField(
            model_name='sellingitems',
            name='sell_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
