# Generated by Django 2.1.7 on 2019-04-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190402_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingitems',
            name='sell_id',
        ),
    ]
