# Generated by Django 2.1.7 on 2019-04-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_sellingitems_sell_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingitems',
            name='sell_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
