# Generated by Django 2.1.7 on 2019-04-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190402_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingitems',
            name='sell_username',
        ),
    ]
