# Generated by Django 2.1.7 on 2019-04-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_sellingitems_sell_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingitems',
            name='sell_username',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
