# Generated by Django 2.1.7 on 2019-04-23 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_sellingitems_sell_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_name', models.CharField(max_length=50)),
                ('sell_username', models.CharField(max_length=50)),
                ('sell_mail', models.CharField(max_length=50)),
                ('sell_description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='sellingitems',
            name='sell_post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 12, 44, 20, 407087), verbose_name='date published'),
        ),
    ]
